from __future__ import annotations

from btc_quant_lab.models import PivotConfig


def _candidate_bounds(cfg: PivotConfig) -> str:
    if cfg.range_mode == "R4":
        return """        candidateTop := math.max(open, close)
        candidateBottom := math.min(open, close)"""
    if cfg.range_mode == "R7":
        return """        candidateTop := bearCandidate ? high[1] : math.max(open, close)
        candidateBottom := bearCandidate ? math.min(open, close) : low[1]"""
    if cfg.range_mode == "R8":
        return """        candidateTop := bearCandidate ? math.max(open[1], close[1]) : high
        candidateBottom := bearCandidate ? low : math.min(open[1], close[1])"""
    raise ValueError(f"unsupported range mode: {cfg.range_mode}")


def _candidate_gate(cfg: PivotConfig) -> str:
    if cfg.motor == "M1":
        return "candidateFound and not pending"
    if cfg.motor == "M3":
        return "candidateFound"
    raise ValueError(f"unsupported motor: {cfg.motor}")


def export_baseline_pine(cfg: PivotConfig, title: str = "BQR Pivot Baseline") -> str:
    """Export the current Python baseline detector to deterministic Pine Script v6.

    The generated indicator mirrors `research/pivots.py`: pending resolution happens
    before candidate creation on each bar, confirmation/invalidation uses close only,
    and M3 replaces an unresolved pending candidate when a new valid transition appears.
    """
    if cfg.min_bars < 1:
        raise ValueError("min_bars must be >= 1")
    if cfg.max_pending < 0:
        raise ValueError("max_pending must be >= 0")

    bounds = _candidate_bounds(cfg)
    gate = _candidate_gate(cfg)
    timed_out = (
        "false"
        if cfg.max_pending == 0
        else f"pendingAge >= {int(cfg.max_pending)}"
    )
    safe_title = title.replace('"', "'")

    return f'''//@version=6
indicator("{safe_title} — {cfg.motor}/{cfg.range_mode}/min{cfg.min_bars}/pend{cfg.max_pending}", overlay=true, max_boxes_count=500, max_labels_count=500)

// Generated by Bitcoin Quant Research Lab.
// Semantics are intentionally frozen to src/btc_quant_lab/research/pivots.py.
// Breakout/invalidation uses CLOSE only; wicks outside the zone do not resolve it.

const string BQR_MOTOR = "{cfg.motor}"
const string BQR_RANGE = "{cfg.range_mode}"
const int BQR_MIN_BARS = {int(cfg.min_bars)}
const int BQR_MAX_PENDING = {int(cfg.max_pending)}

color pendingColor = color.new(color.yellow, 72)
color bearishConfirmedColor = color.new(color.green, 78)   // original visual convention: upper pivot
color bullishConfirmedColor = color.new(color.red, 78)     // original visual convention: lower pivot

var bool pending = false
var int pendingDir = 0
var float pendingTop = na
var float pendingBottom = na
var int pendingIndex = na
var box pendingBox = na

// These counters contain the consecutive run ending on the PREVIOUS bar at the
// beginning of each new bar, which matches _prior_same_color() in the Python engine.
var int bullRun = 0
var int bearRun = 0

bool confirmedBear = false
bool confirmedBull = false
float confirmedTop = na
float confirmedBottom = na
int confirmedAge = na

// 1) Resolve the candidate that already existed before this bar.
if pending
    box.set_right(pendingBox, bar_index)
    int pendingAge = bar_index - pendingIndex
    bool confirmed = pendingDir == -1 ? close < pendingBottom : close > pendingTop
    bool invalidated = pendingDir == -1 ? close > pendingTop : close < pendingBottom
    bool timedOut = {timed_out}

    if confirmed
        confirmedBear := pendingDir == -1
        confirmedBull := pendingDir == 1
        confirmedTop := pendingTop
        confirmedBottom := pendingBottom
        confirmedAge := pendingAge
        box.set_right(pendingBox, bar_index)
        box.set_bgcolor(pendingBox, pendingDir == -1 ? bearishConfirmedColor : bullishConfirmedColor)
        box.set_border_color(pendingBox, pendingDir == -1 ? color.green : color.red)
        pending := false
        pendingDir := 0
        pendingTop := na
        pendingBottom := na
        pendingIndex := na
        pendingBox := na
    else if invalidated or timedOut
        box.delete(pendingBox)
        pending := false
        pendingDir := 0
        pendingTop := na
        pendingBottom := na
        pendingIndex := na
        pendingBox := na

// 2) Detect a new transition using only the prior run and the current candle.
int priorBull = bullRun
int priorBear = bearRun
bool bearCandidate = bar_index > 0 and close < open and priorBull >= BQR_MIN_BARS
bool bullCandidate = bar_index > 0 and close > open and priorBear >= BQR_MIN_BARS
bool candidateFound = bearCandidate or bullCandidate

float candidateTop = na
float candidateBottom = na
int candidateDir = 0

if candidateFound
    candidateDir := bearCandidate ? -1 : 1
{bounds}

// 3) M1 blocks while pending; M3 replaces the pending candidate.
if {gate}
    if pending and not na(pendingBox)
        box.delete(pendingBox)
    pending := true
    pendingDir := candidateDir
    pendingTop := candidateTop
    pendingBottom := candidateBottom
    pendingIndex := bar_index
    pendingBox := box.new(
         left=bar_index,
         top=pendingTop,
         right=bar_index,
         bottom=pendingBottom,
         bgcolor=pendingColor,
         border_color=color.yellow)

// 4) Update the consecutive-color state only after candidate generation.
bullRun := close > open ? priorBull + 1 : 0
bearRun := close < open ? priorBear + 1 : 0

plotshape(confirmedBear, title="Pivote bajista confirmado", style=shape.triangledown, location=location.abovebar, color=color.green, size=size.tiny, text="B")
plotshape(confirmedBull, title="Pivote alcista confirmado", style=shape.triangleup, location=location.belowbar, color=color.red, size=size.tiny, text="A")

alertcondition(confirmedBear, "BQR bearish pivot", "BQR bearish pivot confirmed")
alertcondition(confirmedBull, "BQR bullish pivot", "BQR bullish pivot confirmed")
'''
